AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 2.6
  Exclude:
    - "Gemfile"

Metrics/BlockLength:
  IgnoredMethods: ["describe", "context"]

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
